Repository caicloud/loadbalancer-provider, pull requests merged in 2019-08, with the labels that each got.

#81 feat: update vendor to add proxy http/https port
  Gopkg.lock
  vendor/github.com/caicloud/clientset/informers/clever/v1alpha2/interface.go
  vendor/github.com/caicloud/clientset/informers/clever/v1alpha2/mlneurontaskowner.go
  vendor/github.com/caicloud/clientset/informers/generic.go
  vendor/github.com/caicloud/clientset/informers/resource/v1beta1/interface.go
  vendor/github.com/caicloud/clientset/informers/resource/v1beta1/nodeclaim.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/clever/v1alpha2/clever_client.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/clever/v1alpha2/generated_expansion.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/clever/v1alpha2/mlneurontaskowner.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/resource/v1beta1/generated_expansion.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/resource/v1beta1/nodeclaim.go
  vendor/github.com/caicloud/clientset/kubernetes/typed/resource/v1beta1/resource_client.go
  vendor/github.com/caicloud/clientset/listers/clever/v1alpha2/expansion_generated.go
  vendor/github.com/caicloud/clientset/listers/clever/v1alpha2/mlneurontaskowner.go
  vendor/github.com/caicloud/clientset/listers/resource/v1beta1/expansion_generated.go
  vendor/github.com/caicloud/clientset/listers/resource/v1beta1/nodeclaim.go
  vendor/github.com/caicloud/clientset/pkg/apis/clever/v1alpha2/consts.go
  vendor/github.com/caicloud/clientset/pkg/apis/clever/v1alpha2/register.go
  vendor/github.com/caicloud/clientset/pkg/apis/clever/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/clever/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/evaluation/v1alpha1/register.go
  vendor/github.com/caicloud/clientset/pkg/apis/evaluation/v1alpha1/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/evaluation/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/cluster.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/const.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/extendedresource.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/network.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/register.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/storage.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/serving/v1alpha1/doc.go
  vendor/github.com/caicloud/clientset/pkg/apis/serving/v1alpha1/register.go
  vendor/github.com/caicloud/clientset/pkg/apis/serving/v1alpha1/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/tenant/v1alpha1/type.go
  vendor/github.com/caicloud/clientset/pkg/apis/tenant/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#77 feat(appgateway): add azure application gateway function for kaide
  cmd/azure/main.go
  core/provider/controller.go
  core/provider/types.go
  providers/azure/appgateway.go
  providers/azure/azure.go
  providers/azure/client/client.go
  providers/azure/client/types.go
  providers/azure/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#80 fix: azure error parse
  providers/azure/azure.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#83 chore: OWNERS + hicaistar and sinksmell
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#84 chore: update vendor
  Gopkg.lock
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#82 feat: mutable default http/https port
  build/ipvsdr/keepalived.tmpl
  core/provider/ports.go
  providers/ipvsdr/ipvsdr.go
  providers/ipvsdr/keepalived.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#85 feat(appgateway): add app gateway http setting and probe
  providers/azure/appgateway.go
  providers/azure/azure.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#86 [KAIDE-14]fix(appgateway): fix probe id not found bug
  providers/azure/appgateway.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#88 chore(vendor): update clientset to support httport and portrange
  Gopkg.lock
  vendor/github.com/caicloud/clientset/kubernetes/typed/resource/v1beta1/network.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/cluster.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/const.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/network.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/storage.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/tenant/v1alpha1/type.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#89 feat: mutable default http/https port
  build/ipvsdr/keepalived.tmpl
  core/provider/ports.go
  providers/ipvsdr/ipvsdr.go
  providers/ipvsdr/keepalived.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#90 feat: delete Jenkinsfile
  Jenkinsfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#87 [KAIDE-18]fix(appgateway): fix delete rule error
  providers/azure/appgateway.go
  providers/azure/azure.go
  providers/azure/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
