Repository caicloud/loadbalancer-provider, pull requests merged in 2019-03, with the labels that each got.

#33 refactor(net): rewrite core/pkg/net
  Gopkg.lock
  Gopkg.toml
  core/pkg/net/net.go
  providers/ipvsdr/ipvsdr.go
  providers/ipvsdr/keepalived.go
  vendor/github.com/zoumo/golib/LICENSE
  vendor/github.com/zoumo/golib/netutil/net.go
  vendor/k8s.io/client-go/util/retry/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#35 fix(ipvs): wait for ipvs persistent connections cache expiring in backup nodes
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/ipvsdr.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#34 feat(azure): sync azure security group and implement asynchronous pre-delete
  core/provider/controller.go
  providers/azure/azure.go
  providers/azure/client/client.go
  providers/azure/client/types.go
  providers/azure/loadbalancer.go
  providers/azure/utils.go
  vendor/k8s.io/client-go/util/retry/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#39 fix(ipvs): wait for ipvs persistent connections cache expiring in backup nodes
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/ipvsdr.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#40 refactor(ipvs): replace exec.Command with golib/shell
  Gopkg.lock
  providers/ipvsdr/ipvscache.go
  vendor/github.com/zoumo/golib/shell/shell.go
  vendor/k8s.io/client-go/util/retry/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#44 fix(ipvs): skip connections cache checking in master
  providers/ipvsdr/ipvscache.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#45 refactor: reading connections from file instead of ipvsadm
  providers/ipvsdr/ipvscache.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#49 fix(machine): delete machine infomer sync
  core/provider/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none

#52 chore(owner): update owner
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#42 [CPS-940] fix(failed): delete finalizer though azure lb if empty
  providers/azure/azure.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
