Repository caicloud/loadbalancer-provider, pull requests merged in 2019-04, with the labels that each got.

#55 [CPS-1500] fix(aks): get correct vm info from aks cluster
  providers/azure/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#58 fix: correct node priority in vrrp
  providers/ipvsdr/ipvsdr.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#57 [CPS-1639] fix: retry when get configMap failed
  providers/azure/azure.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
