Repository caicloud/loadbalancer-provider, pull requests merged in 2019-09, with the labels that each got.

#91 fix: remove useless code about ingress sidecar
  cmd/ingress/main.go
  providers/ingress/sidecar.go
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#92 refactor: format project
  .caimake/update.sh
  .golangci.yml
  Makefile
  build/azure/Dockerfile
  build/ingress/Dockerfile
  build/ipvsdr/Dockerfile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#93 refactor: fix lint code
  cmd/azure/main.go
  cmd/ingress/main.go
  cmd/ipvsdr/main.go
  core/pkg/arp/cache.go
  core/pkg/arp/cache_linux.go
  core/provider/controller.go
  pkg/execd/execd.go
  providers/azure/azure.go
  providers/azure/loadbalancer.go
  providers/azure/utils.go
  providers/ingress/sidecar.go
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/ipvsdr.go
  providers/ipvsdr/keepalived.go
  providers/ipvsdr/util.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#95 fix: disable cgo so binary can run on alpine image
  Makefile
  build/ipvsdr/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
