Repository caicloud/loadbalancer-provider, pull requests merged in 2020-09, with the labels that each got.

#164 fix: use AlternateMode=None by default for f5 dns
  providers/f5lb/f5dns.go
  vendor/github.com/hanxueluo/go-bigip/gtm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#165 chore(vendor): use forked infoblox-go-client lib
  Gopkg.lock
  Gopkg.toml
  providers/f5lb/infoblox_lib.go
  providers/f5lb/infobloxdns.go
  vendor/github.com/hanxueluo/infoblox-go-client/LICENSE
  vendor/github.com/hanxueluo/infoblox-go-client/connector.go
  vendor/github.com/hanxueluo/infoblox-go-client/lock.go
  vendor/github.com/hanxueluo/infoblox-go-client/object_manager.go
  vendor/github.com/hanxueluo/infoblox-go-client/objects.go
  vendor/github.com/hanxueluo/infoblox-go-client/record_a.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#166 fix: make sure ltm pool member update when delete node
  providers/f5lb/f5ltm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#169 fix: new pool name rule
  core/provider/types.go
  providers/f5lb/f5dns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#170 fix(infoblox): override ValidateConnector
  providers/f5lb/infoblox_lib.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#171 chore: update vendor to remove unsupport fields in infoblox v2.2
  Gopkg.lock
  vendor/github.com/hanxueluo/infoblox-go-client/record_a.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#172 feat(*): upgrade golang image to 1.13-security
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#174 feat(*): upgrade golang image to 1.12-security
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#176 fix: fix rule map leak
  providers/f5lb/f5dns.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#175 fix: do not retrieve all record when sync rules
  providers/f5lb/common.go
  providers/f5lb/f5dns.go
  providers/f5lb/f5lb.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
