Repository caicloud/loadbalancer-provider, pull requests merged in 2020-08, with the labels that each got.

#146 fix: handle ingress delete
  providers/f5lb/f5lb.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#148 fix: increase fresh period of f5 token to 18min
  providers/f5lb/f5dns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#149 chore(vendor): update vendor go-bigip
  Gopkg.lock
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/hanxueluo/go-bigip/gtm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#150 feat: support l4 ltm and release l4 dns
  core/provider/controller.go
  core/provider/types.go
  providers/azure/azure.go
  providers/f5lb/common.go
  providers/f5lb/f5dns.go
  providers/f5lb/f5lb.go
  providers/f5lb/f5ltm.go
  providers/f5lb/infobloxdns.go
  providers/ingress/sidecar.go
  providers/ipvsdr/ipvsdr.go
  vendor/github.com/infobloxopen/infoblox-go-client/record_a.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#152 fix: always use basic auth
  providers/f5lb/f5dns.go
  providers/f5lb/f5ltm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#153 fix: create l4 pool only if l4 vs set
  providers/f5lb/f5ltm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#155 fix: update wip only if change
  providers/f5lb/f5dns.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#157 chore(owners): add reviewer VincentGuoCQ
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#156 fix: ensure l7 dns records at beginning
  providers/f5lb/common.go
  providers/f5lb/f5dns.go
  providers/f5lb/f5lb.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#158 fix: delete dns record only if "l47" match
  providers/f5lb/f5dns.go
  providers/f5lb/infobloxdns.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#159 fix: should return
  providers/f5lb/f5lb.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#160 fix: report error if no object found
  providers/f5lb/infoblox_lib.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#161 chore(owners): add approver and reviewer VincentGuoCQ
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#162 fix: only ensure all l7 at first time
  providers/f5lb/f5lb.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#163 fix: not use switch when no rule
  providers/f5lb/f5ltm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
