Repository caicloud/loadbalancer-provider, pull requests merged in 2020-03, with the labels that each got.

#112 feat: support ipv6 and support multiple net planes
  build/ipvsdr/Dockerfile
  build/ipvsdr/keepalived.tmpl
  cmd/ipvsdr/main.go
  cmd/ipvsdr/options.go
  core/pkg/arp/cache.go
  core/pkg/arp/cache_darwin.go
  core/pkg/arp/cache_darwin_test.go
  core/pkg/arp/cache_linux.go
  core/pkg/arp/cache_linux_test.go
  core/pkg/node/node.go
  core/provider/controller.go
  core/provider/ports.go
  core/provider/types.go
  providers/azure/azure.go
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/ipvsdr.go
  providers/ipvsdr/keepalived.go
  providers/ipvsdr/keepalived_test.go
  providers/ipvsdr/nodenetwork.go
  providers/ipvsdr/util.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/validation.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/zz_generated.deepcopy.go
Labels: approved, caicloud-cla: yes, do-not-merge/hold, release-note-none, size/XXL

#113 fix: improve solution of packet loop in ipvsdr
  cmd/ipvsdr/main.go
  cmd/ipvsdr/util.go
  providers/ipvsdr/ipvscache.go
  providers/ipvsdr/ipvsdr.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#115 [CPS-6049] build: switch to go mod
  Gopkg.lock
  Gopkg.toml
  Makefile
  go.mod
  go.sum
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#117 upgrade golang version to 1.13.6 & upgrade golangci-lint
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
